### ISSUE TITLE
Build error on Manjaro Linux with Vulkan Header 1.2.136

### ISSUE THREAD

**Issue by unknownue** [nvpro-samples/nvpro_core#18]
I tried to build the code of [vk_raytracing_tutorial_KHR](https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR), but got compile error in this repo.

Build context:
```
System: Manjaro Linux 19.02
Kernel: 5.4.28
Driver version: 440.66.08
gcc version: 9.3.0
```

Build process output:
```
[ 15%] Building CXX object shared_sources/CMakeFiles/shared_sources.dir/imgui/imgui_widgets.cpp.o
[ 15%] Building CXX object shared_sources/CMakeFiles/shared_sources.dir/imgui/imgui_orient.cpp.o
[ 15%] Building CXX object shared_sources/CMakeFiles/shared_sources.dir/imgui/imgui_impl_gl.cpp.o
[ 16%] Building CXX object shared_sources/CMakeFiles/shared_sources.dir/imgui/imgui_impl_vk.cpp.o
[ 16%] Linking CXX static library /home/unknownue/Workspace/Examples/NVIDIA/bin_x64/libshared_sources_gl_vk.a
make[2]: Leaving directory '/home/unknownue/Workspace/Examples/NVIDIA/vk_raytracing_tutorial_KHR/build'
[ 16%] Built target shared_sources
make[2]: Entering directory '/home/unknownue/Workspace/Examples/NVIDIA/vk_raytracing_tutorial_KHR/build'
Scanning dependencies of target vk_ray_tracing__advance_KHR
make[2]: Leaving directory '/home/unknownue/Workspace/Examples/NVIDIA/vk_raytracing_tutorial_KHR/build'
make[2]: Entering directory '/home/unknownue/Workspace/Examples/NVIDIA/vk_raytracing_tutorial_KHR/build'
[ 16%] Building CXX object ray_tracing__advance/CMakeFiles/vk_ray_tracing__advance_KHR.dir/hello_vulkan.cpp.o
In file included from /home/unknownue/Workspace/Examples/NVIDIA/vk_raytracing_tutorial_KHR/ray_tracing__advance/hello_vulkan.cpp:40:
/home/unknownue/Workspace/Examples/NVIDIA/vk_raytracing_tutorial_KHR/../shared_sources/nvvkpp/pipeline_vkpp.hpp: In member function ‘vk::Pipeline nvvkpp::GraphicsPipelineGenerator::create(const vk::PipelineCache&)’:
/home/unknownue/Workspace/Examples/NVIDIA/vk_raytracing_tutorial_KHR/../shared_sources/nvvkpp/pipeline_vkpp.hpp:91:41: error: could not convert ‘(&((nvvkpp::GraphicsPipelineGenerator*)this)->nvvkpp::GraphicsPipelineGenerator::device)->vk::Device::createGraphicsPipeline<>((* & cache), ((nvvkpp::GraphicsPipelineGenerator*)this)->nvvkpp::GraphicsPipelineGenerator::pipelineCreateInfo, vk::Optional<const vk::AllocationCallbacks>(nullptr), vk::defaultDispatchLoaderDynamic)’ from ‘vk::ResultValue<vk::Pipeline>’ to ‘vk::Pipeline’
   91 |     return device.createGraphicsPipeline(cache, pipelineCreateInfo);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         |
      |                                         vk::ResultValue<vk::Pipeline>
make[2]: *** [ray_tracing__advance/CMakeFiles/vk_ray_tracing__advance_KHR.dir/build.make:155: ray_tracing__advance/CMakeFiles/vk_ray_tracing__advance_KHR.dir/hello_vulkan.cpp.o] Error 1
make[2]: Leaving directory '/home/unknownue/Workspace/Examples/NVIDIA/vk_raytracing_tutorial_KHR/build'
make[1]: *** [CMakeFiles/Makefile2:390: ray_tracing__advance/CMakeFiles/vk_ray_tracing__advance_KHR.dir/all] Error 2
make[1]: Leaving directory '/home/unknownue/Workspace/Examples/NVIDIA/vk_raytracing_tutorial_KHR/build'
make: *** [Makefile:147: all] Error 2
[unknownue@Arch build]$
```

**Comment by NBickford-NV** [comment]
Interesting, it looks like this might be due to some changes in Vulkan-Hpp - could you let me know which version of the Vulkan SDK you're using (or alternatively, what the value of the `VK_HEADER_VERSION` macro is?

On my local computer, using Vulkan SDK 1.2.131.2 (`VK_HEADER_VERSION` = 131), it looks like `createGraphicsPipeline` returns a `ResultValueType<Pipeline>::type`, which is a `vk::Pipeline`, since we have exceptions enabled:

```
typename ResultValueType<Pipeline>::type createGraphicsPipeline( VULKAN_HPP_NAMESPACE::PipelineCache pipelineCache, const GraphicsPipelineCreateInfo & createInfo, Optional<const AllocationCallbacks> allocator = nullptr, Dispatch const &d = VULKAN_HPP_DEFAULT_DISPATCHER ) const;
```

But on the latest Vulkan-Hpp (`VK_HEADER_VERSION` = 136), it returns a `ResultValue<Pipeline>`:

```
ResultValue<Pipeline> createGraphicsPipeline( VULKAN_HPP_NAMESPACE::PipelineCache pipelineCache, const GraphicsPipelineCreateInfo & createInfo, Optional<const AllocationCallbacks> allocator = nullptr, Dispatch const &d = VULKAN_HPP_DEFAULT_DISPATCHER ) const;
```

It looks like `ResultValue<Pipeline>` has implicit conversion operators to references and constant references to its value in the latest version (seems to be in header version 136, but not in 131, and it's included since I don't think we define `VULKAN_HPP_DISABLE_IMPLICIT_RESULT_VALUE_CAST`) - maybe the issue has something to do with this?

**Comment by unknownue** [comment]
Yes, the  Vulkan header 1.2.136 seems not yet to be compatible.
After specifying a lower version of Vulkan header, it works.


As the additional note, here are the steps I have done to build [vk_raytracing_tutorial_KHR](https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR):

1. Manually clone the Vulkan-Header repo
```shell
$ git clone https://github.com/KhronosGroup/Vulkan-Headers
$ cd Vulkan-Headers
$ git checkout v1.2.135
```
I have tried v1.2.131, v1.2.132, v.1.2.136, but v1.2.135 is the only version that compile.

2. Manually build the latest version of `glslang`
```shell
$ git clone https://github.com/KhronosGroup/glslang
```
Then follow the [build instruction](https://github.com/KhronosGroup/glslang#building) to build `glslangValidator` binary.

3. Start to build vk_raytracing_tutorial_KHR (`$SOME_WHERE` is the repo location of the first two steps)
```shell
(../vk_raytracing_tutorial_KHR/build) $ cmake -DVULKAN_HEADERS_OVERRIDE_INCLUDE_DIR='$SOME_WHERE/Vulkan-Headers/include' -DGLSLANGVALIDATOR=$SOME_WHERE/glslang/build/StandAlone/glslangValidator ..
(../vk_raytracing_tutorial_KHR/build) $ make -j4
```

I also tried the linux SDK v1.2.131.2 from [LunarG](https://vulkan.lunarg.com), but the compiler complained it doesn't support `VK_KHR_ray_tracing`.

**Comment by asuessenbach** [comment]
Hi @unknownue, it should have worked to just replace your vulkan.hpp, with the one currently in [Vulkan-Hpp](https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/vulkan/vulkan.hpp).

The issue here is, as Neil already mentioned, that the C++-API of some functions has changed, while the C-API did not. In C, "only" the semantics of those functions has slightly changed: Before, they only supported exactle one result as success (VK_SUCCESS), but now they support more than one. And thus, the C++-API changed for those functions, as the result code had to be returned as well.

But the latest vulkan.hpp does support an implicit cast from the ResultValue<> structure to the Value type, that is, no changes should be needed for your case.
Besides, of course, the handling of any other success code.

**Comment by unknownue** [comment]
Thanks @asuessenbach , by just replacing the vulkan.hpp, it does compile without any warnings. And now I need not override the default `glslangValidator`.
I think this issue can be closed now.
