### ISSUE TITLE
Vulkan doesn't start on Intel GPU

### ISSUE THREAD

**Issue by Andreyogld3d** [nvpro-samples/nvpro_core#36]
Hi, Intel UHD 630, last driver http://vulkan.gpuinfo.org/displayreport.php?id=14044

We can fix problem here:

https://github.com/nvpro-samples/nvpro_core/blob/master/nvvk/context_vk.cpp#L454
fox example replace "return false;" -> continue;

After fix it can gbe run on Intel UHD 630:

![image](https://user-images.githubusercontent.com/8597425/153593094-a7a55573-3cd5-4364-b235-6032b7ce5077.png)
![image](https://user-images.githubusercontent.com/8597425/153593224-7b028b06-2a79-4122-9b5b-931988818792.png)

**Comment by pixeljetstream** [comment]
Thanks for your findings, we design most of our samples to have 3 independent queues, this is not supported by some older Intel drivers/devices. While it is true that some samples can be made run, it's not something we generally maintain, as some samples and utilities might assume multiple queues.

The "proper" fix is to change those samples that support using a single queue alone, so that their nvvk::ContextInfo setup only puts a single queue in the request (current default constructor of nvvk::ContextInfo is requesting the three independent queues).
