### ISSUE TITLE
Add an option to disable Vulkan beta features

### ISSUE THREAD

**Issue by Venemo** [nvpro-samples/nvpro_core#41]
`nvpro-core` currently unconditionally uses some Vulkan beta features (such as video) but Vulkan beta changes frequently and `nvpro-core` isn't updated frequently enough to reflect current changes.

Please make relying on beta features optional and don't require them for samples which don't use these features.

**Comment by expenses** [comment]
I can second this. I'm currently getting `error: ‘VkVideoBindMemoryKHR’ does not name a type` when trying to build https://github.com/nvpro-samples/gl_vk_meshlet_cadscene.

**Comment by Venemo** [comment]
This MR updates the code to work with very latest Vulkan headers: https://github.com/nvpro-samples/nvpro_core/pull/40

**Comment by mklefrancois** [comment]
Thanks for bringing this up, we will update the `extensions_vk.cpp`. Note that this file can be updated by running ` python extensions_vk.py`, it will pick up the lastest information from the installed Vulkan SDK.

**Comment by Venemo** [comment]
@mklefrancois That's exactly what I did for the aforementioned PR

**Comment by NBickford-NV** [comment]
Hi all, we've just merged Venemo's pull request, and also made it so that `extensions_vk.py` doesn't generate files with prototypes for beta features by default!

It also has a new `--beta` flag (and a `--help` option!), so it's possible to generate prototypes for provisional extensions by running

```
extensions_vk.py --beta
```

This should fix the build issue with gl_vk_meshlet_cadscene. It looks like vk_video_decode's not quite building with the Vulkan 1.3.224 headers yet — I'm going to see what can be done there next week (as this Thursday and Friday are company-wide days off).

Thanks!

**Comment by Venemo** [comment]
Thank you Neil, you effort is much appreciated.
