### ISSUE TITLE
Question. Which BRDF/BSDF/BTDF models used?

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#72]
1. Is Disney or Oren-Nayar can be implemented vs Lambert?
2. Is these models are phisical based?
3. Which models is used for specular and dielectrics?
4. Is Anisotropic Torrance-Sparrow BRDF is better then yours?

**Comment by NBickford-NV** [comment]
Hi @tigrazone ! We've got some updated docs coming soon that will answer these questions in more detail. Here's the short answers for now:

1. Yep, though a user would have to modify the code at the moment! We use Lambert for our diffuse lobe because it's referenced in the glTF specification at https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#diffuse-brdf (although this is an informative section, so presumably renderers could use a different diffuse BRDF).
2. Yep! They're physically based.
3. Our glossy lobes are generally single-scattering (multi-scattering may be a future improvement) GGX (same as Trowbridge-Reitz) with an uncorrelated Smith shadowing-masking function, and glTF models dielectrics using a Fresnel mixture of glossy and diffuse lobes. The exception is the sheen lobe, which uses [Conty and Kulla's "Charlie" sheen](https://blog.selfshadow.com/publications/s2017-shading-course/#course_content)
and a V-cavity shadowing-masking function.
4. Trowbridge-Reitz/GGX is probably better than the Torrance-Sparrow NDF, for most materials. But we do use the concept of a microfacet model from the Torrance-Sparrow paper.
  * Torrance and Sparrow's 1967 paper [Theory for Off-Specular Reflection from Roughened Surfaces](https://www.graphics.cornell.edu/~westin/pubs/TorranceSparrowJOSA1967.pdf) uses a normal distribution function (NDF) of `exp(-(c * a)^2)`, where `a` is the angle between the half-vector and the normal (equation (13)). The Torrance-Sparrow paper's the foundation for microfacet BSDFs, but the choice of NDF here is rather arbitrary (and note that this model has a nonzero chance of including backwards-facing microfacets).
    * Note: There might be some terminological confusion here! "Torrance-Sparrow" can refer to both the concept of using a microfacet model for BSDFs, and to the specific NDF they use. We combine Torrance-Sparrow microfacet theory with the Trowbridge-Reitz NDF. If you weren't referring to the Torrance-Sparrow NDF, then the remaining bullet points aren't useful since they're talking only about NDFs.
  * Torrance-Sparrow is conceptually similar to the "Beckmann" NDF (I believe from Beckmann and Spizzichino's 1963 "The Scattering of Electromagnetic Waves from Rough Surfaces", though I haven't checked the book), which uses a Gaussian but in *slope-space* (i.e. `h / dot(h, n)`) was in wide use for a while, but was eventually supplanted by [the Trowbridge-Reitz 1975 model](https://www.cs.cornell.edu/~srm/publications/EGSR07-btdf.html) (later reinvented as GGX in 2007 by Walter et al.), which we use.
  * Trowbridge-Reitz has "higher tails" than Beckmann, which matches Trowbridge-Reitz and Walter's model materials of ground glass better (GGX stands for "ground glass unknown", in fact! Both Walter et al. and Trowbridge-Reitz [coincidentally measured ground glass](http://www.flycooler.com/download/SupplementalEllipsoidNDF.pdf).) Here's a comparison of Beckmann and Trowbridge-Reitz against real-world data from the latter's paper:

![image](https://github.com/user-attachments/assets/d67275ff-8e55-480a-9c41-a4738ccd9993)

  * But not all materials we see in the world are ground glass-like. Usually a combination of multiple lobes is good enough to look realistic, but there's some materials that still aren't fit well (these usually appear in BRDF fitting papers).

**Comment by tigrazone** [comment]
Thank you for explaination.
It was very informative and usefull

**Comment by NBickford-NV** [comment]
Thank you! The docs update I mentioned is now live; you'll find the new docs at https://github.com/nvpro-samples/nvpro_core/blob/master/nvvkhl/shaders/README.md#bsdf_functionsh, which are auto-generated from inline comments in https://github.com/nvpro-samples/nvpro_core/blob/master/nvvkhl/shaders/bsdf_functions.h.
