### ISSUE TITLE
is doubleSided not supported by  vk_gltf_renderer?

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#73]
is it possible to implement doubleSided?

**Comment by tigrazone** [comment]
[scene](https://drive.google.com/file/d/1ROSuis-kB9SCNjtr4Ek_thBN_8Ay6AYx/view?usp=sharing) and [camera settings](https://drive.google.com/file/d/1UEumf-F4mNAcozWBVsipqpoZnMK6es74/view?usp=sharing) to reproduce

camera 11
rendered by vk_raytrace
![vk_raytraced](https://github.com/user-attachments/assets/0bcbeed9-978f-4b72-828f-469aeb57d5eb)

rendered by vk_gltf_renderer
![vk_gg](https://github.com/user-attachments/assets/4c1fa6bb-6a2d-4593-8aaf-628449e98d0f)

**Comment by mklefrancois** [comment]
Thanks for reporting the issue. In fact the problem is the miss interpretation of the attenuation distance. The default value is infinity as described in [KHR_material_vollume](https://github.com/DassaultSystemes-Technology/glTF/tree/KHR_materials_volume/extensions/2.0/Khronos/KHR_materials_volume#properties) but we were looking for a default value as 0.0. 

vk_raytrace was setting the default to 0.0 and looking for 0.0, but gltf_renderer set it the the proper default, but was looking for the wrong value. 

Could you verify if modifying `absorptionCoefficient()` to the following fixes it also on your side.
```
vec3 absorptionCoefficient(PbrMaterial mat)
{
  float tmp1 = mat.attenuationDistance;
  if (tmp1 <= 0.0F || tmp1 >= INFINITE)
  {
    return vec3(0.0F, 0.0F, 0.0F);
  }
  return -vec3(log(mat.attenuationColor.x), log(mat.attenuationColor.y), log(mat.attenuationColor.z)) / tmp1;
}
```

**Comment by mklefrancois** [comment]
Looking at the issue more closely, this might not be all. Still investigating

**Comment by mklefrancois** [comment]
The current scene contains glass objects that are incorrectly configured:
- Objects have both `transmissionFactor` and `thicknessFactor` properties
- `thicknessFactor` is set > 0.0, indicating solid transparent objects
- However, the geometry isn't actually solid

This creates an edge case not explicitly covered in the glTF specification. The ray tracing behavior should involve entering and exiting the transparent medium for solid objects, but this isn't possible with non-solid geometry.


We can use the `doubleSided` flag as an indicator:
- When `true`: treat as thin-walled transparent surface (no medium entry/exit)
- When `false`: treat as solid transparent object (with medium entry/exit)

[glTF-Sample-Assets](https://github.com/KhronosGroup/glTF-Sample-Assets) shows solid transparent objects consistently use `doubleSided: false`
Maybe this pattern suggests `doubleSided` can reliably indicate the intended transparency behavior.

Note: The scene previously appeared correct in `vk_raytrace` due to incorrect absorption handling, masking this issue.

**Comment by tigrazone** [comment]
Ок. How to reconfigure glass materials to get same as vk_raytrace image?

**Comment by mklefrancois** [comment]
There's no way to correctly represent thick glass behavior with a single plane and thicknessFactor > 0.0, as it violates the physics of ray tracing - the ray needs both an entry and exit point. 

I will make an update, that will be using the doubleSide flag as an indicator of such geometry. 

This will be looking like this:
![image](https://github.com/user-attachments/assets/7cee88c5-ac61-4b10-b1cb-d7f321eee603)

Meanwhile, I found and fixed another issue. It is subtile but the inner reflection of a texture on top of glass will be properly reflected.
![image](https://github.com/user-attachments/assets/dde70884-bcd2-4b09-aed7-f0633521c438)

**Comment by tigrazone** [comment]
good news!

**Comment by mklefrancois** [comment]
An update was done in both nvpro-core and gltf_renderer.
Could you please give it a try?

**Comment by tigrazone** [comment]
ABSOLUTELY better. thank you!

**Comment by tigrazone** [comment]
[some scenes](https://drive.google.com/file/d/1iIxshRkq02dZzCnUx599YL6WkV8dPIay/view?usp=sharing) looks strange with update.

prev renderer
![prev](https://github.com/user-attachments/assets/42b42e62-3d0d-4f1f-b5ea-b8f62432a1b2)

updated
![new](https://github.com/user-attachments/assets/cbb0674c-fd05-4c5f-af16-d2dd0dd45ea5)

is it can be fixed?

**Comment by mklefrancois** [comment]
I suspected something like this might happen because the double-sided flag was not part of the glTF specification.

Looking into this will take more time. For now, could you try a local undo of the one-line change in the gltf renderer? This might help determine if reverting to the previous state of that file fixes things.

**Comment by tigrazone** [comment]
I just git reset COMMIT_ID --hard and this make me previous image

**Comment by tigrazone** [comment]
maybe try to change
[        if(isTransmission && (material.doubleSided == 0))](https://github.com/nvpro-samples/vk_gltf_renderer/blob/c0bfdc7f1f40f6febd1dfb94e68317c2674cee79/shaders/rt_common.h#L328)
to
`if(isTransmission || (material.doubleSided == 1))`

maybe it wrong. I think needed to check ray side

**Comment by tigrazone** [comment]
one more idea
replace whole condition 
```
        if(isTransmission && (material.doubleSided == 0))
        {
          isInside = !isInside;
        }
```
to
`
isInside = dot(r.direction, hit.nrm) < 0;`

rendered with this fix
![lux-nv](https://github.com/user-attachments/assets/2464a473-ceee-4ec0-9eb9-a002da3ee02c)

**Comment by tigrazone** [comment]
scene with luxball rendered by my fork of [gkNextRenderer](https://github.com/gameknife/gkNextRenderer)
where this scene was taken. This renderer not support yet NEE, MIS, not well support complex materials.
Original repo not use accumulation. My fork use accumulation
![lux-gknextrender](https://github.com/user-attachments/assets/41a02670-ba72-46dd-9078-331f569c2166)

**Comment by mklefrancois** [comment]
As mentioned earlier, using the double sided to deal with fake solid objects could be an issue.
This scene shows it, because the material of the glass is set to be double-sided, contrary to many other scene. 

Removing the double sided flag renders the scene as expected. But this isn't a solid solution for those cases. Still investigating what could be the best for all cases.  

![image](https://github.com/user-attachments/assets/9f8423aa-c90a-45dd-9a40-117ef868f212)


![image](https://github.com/user-attachments/assets/18bd3d38-bb87-45a3-9129-c869b21544fe)

**Comment by mklefrancois** [comment]
With the latest update, this issue should be fixed. @tigrazone, can you please confirm?

**Comment by tigrazone** [comment]
with latest update all scenes rendered ok w/o scene changes and tune ups
![bistro-inside](https://github.com/user-attachments/assets/6446523d-0300-4327-9924-91ca71032d20)

![compare-tra](https://github.com/user-attachments/assets/4057f13c-8f13-4b45-87a2-1d1da1693d92)

![luxx](https://github.com/user-attachments/assets/c9dd1fce-f34a-4519-a4b6-b027aab63a83)

### thank you!
