### ISSUE TITLE
is NormalTangentMirrorTest rendered incorrect?

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#76]
rendered by vk_gltf_renderer
![image](https://github.com/user-attachments/assets/8a9f8491-a674-4a65-b92c-9b01602e0ff0)

model is taken from [glTF-Sample-Assets](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/NormalTangentMirrorTest)
and reference render
![image](https://github.com/KhronosGroup/glTF-Sample-Assets/raw/main/Models/NormalTangentMirrorTest/screenshot/screenshot-larger.png)

**Comment by tigrazone** [comment]
same problem with [NormalTangentTest](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/NormalTangentTest)
![image](https://github.com/user-attachments/assets/cfe31b29-564e-4dde-b060-3c199fdea059)

reference
![image](https://github.com/KhronosGroup/glTF-Sample-Assets/raw/main/Models/NormalTangentTest/screenshot/screenshot-larger.png)

**Comment by mklefrancois** [comment]
Strong normal maps in ray tracing can produce visible artifacts, especially on flat surfaces, due to the fundamental differences between ray tracing and rasterization approaches.

When light hits a real curved surface (as shown in the top diagram), the rays bounce off naturally, following the physical shape. The challenge with normal maps on flat surfaces (bottom diagram) is that they tell the light to bounce as if it were hitting a curve. In ray tracing, this can cause reflected rays to intersect back into the surface itself - something that wouldn't happen in reality. These invalid self-intersections show up as black spots in the final render.

This issue is specific to ray tracing because it accurately simulates light paths and geometry intersections. Rasterization with cube maps handles things differently - instead of calculating actual ray bounces, it simply looks up colors from the environment map based on the normal direction. That's why normal-mapped reflections can look convincing in rasterized renders, even though they're physically inaccurate.

While rasterizing with strong normal maps produces nice visual results, creating the same look with raytracing remains a challenge due to its physical base. This illustrates the common trade-off between physical accuracy and artistic control in different rendering approaches.

![image](https://github.com/user-attachments/assets/9653e8a1-1bb4-4974-9373-2ad5db00997c)
