### ISSUE TITLE
wrong kitchen.gltf

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#77]
I try to load kitchen scene from https://github.com/NVIDIAGameWorks/Path-Tracing-SDK-Media for test support of dds files.
gltf file use png and jpg but really dds file in folder.
I replace .png and .jpg to .dds in kitchen.gltf
Also I replaced %20 to space symbol and try to open file with vk_gltf_renderer.
Many pink color vs reals dds textures.
Messages:
![image](https://github.com/user-attachments/assets/a213d639-a112-45a3-aba4-939814d7e1d1)
I cant find these files in folder

**Comment by mklefrancois** [comment]
The Path-Tracing-SDK-Media is unfortunately only designed for use with https://github.com/NVIDIAGameWorks/RTX-Path-Tracing which will first try to load .dds variant even if .png is listed. 

It would be possible to manually modify the scene and use the [MSFT_texture_dds ](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/MSFT_texture_dds/README.md) extension. This way the scene would load everywhere, but would display properly only if the extension is supported. 

Please file an issue directly to RTX-Path-Tracing.

**Comment by mklefrancois** [comment]
Please note that those scenes uses a .json and are patching the scene after loading it.

**Comment by NBickford-NV** [comment]
Just to quickly elaborate on this: We support reading DDS files, but it looks like the kitchen scene doesn't provide `Image.dds`, `Image-1.dds`, `Image-2.dds`, or `Image-3.dds`. That's why we render them with our default pink "texture could not be found" image. Nv_dds' errors are because it's being passed a zero-length buffer when that happens.
