### ISSUE TITLE
broken tangents after last commit

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#79]
I render [AnisotropyStrengthTest](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/AnisotropyStrengthTest) with my [pack tangent in different way](https://github.com/tigrazone/nvpro_core/commit/675107cfba3e8357623d2a062519c53f4ea2a5ff) and have buggy image
![AnisotropyStrengthTest-my](https://github.com/user-attachments/assets/d7030466-583a-4444-8f9c-840fa35920a0)

original render w/o my changes are same
![AnisotropyStrengthTest-ori](https://github.com/user-attachments/assets/3ad24868-0bf2-42f3-8c30-8ba1b2f28498)

i.e. original renderer was broken on last commit.
please fix

**Comment by NBickford-NV** [comment]
It seems more's broken here than the tangents -- AnisotropyStrengthTest should show a grid of spheres. I've confirmed this with the latest vk_gltf_renderer and will analyze further.

**Comment by tigrazone** [comment]
What is new in vk_gltf_renderer?
I dont understand logic of new work with shadows and so.
I just understand new vk_gltf_renderer start to use gaussian filter on camera ray? What more is changed? I ask because no changelog after new versions is created. Just "Bulk change #####"

**Comment by mklefrancois** [comment]
@NBickford-NV made a fix and the repositories were updated. 

As for the list of changes, we do not usually list them when we are updating GitHub, but maybe something to consider for the future. 

Here are a few of the changes:
- Shadow going through transparent material (no caustics)
- Changes in how UI present data
- Using compute queue instead of a second graphic when loading scenes
- Better light sampling
- Better Sun & Sky sampling
- Global descriptor set (avoid recreating pipelines, using cached instead)
- Adding SER for the RTX raytracer
- Adding persistance for tonemapper type
- Better control on the camera aperture for various scene size
- Add support for Specular-Glossiness (closest hit, any hit)
- Gaussian sampling filter
- Adding aftermath support
- Fixing MikkTSpace tangent generation
- Avoid issues with KHR_animation_pointer
- Allow editing the camera up vector
- Put application on idle when minimized
- Avoid copy of data, use references instead
- Adding morph animation
- Compute tangents for mesh requiring them (material with normalmap)

**Comment by tigrazone** [comment]
> * Shadow going through transparent material (no caustics)

In which cases it can be used?
Is it can be switched off?
Please give scene file for test this feature

**Comment by mklefrancois** [comment]
It renders this

![image](https://github.com/user-attachments/assets/4e4e138c-3823-4887-be9f-c7c3d66bf6a4)

instead of

![image](https://github.com/user-attachments/assets/38a21fc3-e8eb-42f6-b9e7-5545e811c21f)

**Comment by tigrazone** [comment]
> As for the list of changes, we do not usually list them when we are updating GitHub, but maybe something to consider for the future

Is it possible to add these features to changelog for every commit?

**Comment by tigrazone** [comment]
1. is transparent shadows not a fake?

2. please describe how these sampling goes to be better
> * Better light sampling
> * Better Sun & Sky sampling
